[workspace]
members = [
    "main",
    "hacspec-examples/chacha20",
    "hacspec-examples/chacha20-rfc7539",
    "hacspec-examples/poly1305",
]

default-members = [
    "main",
    "hacspec-examples/chacha20",
    "hacspec-examples/chacha20-rfc7539",
    "hacspec-examples/poly1305",
]
